### ISSUE TITLE
Training and validation datasets

### ISSUE THREAD

**Issue by ahounkanrin** [xtudbxk/em-adapt-tensorflow#1]
Hi @xtudbxk 

I have been trying to run  your code for em-adapt-tensorflow using the VOC2012 as provided on the  PASCAL website  without success.  
Could you please help with the link to the version of PASCAL VOC12 dataset you used for training and validation? I believe it's an augmented version of VOC2012 but I couldn't manage to get it from the PASCAL official website.

**Comment by xtudbxk** [comment]
You can find the extra dataset from [SBD](http://home.bharathh.info/pubs/codes/SBD/download.html).

**Comment by XZNWU** [comment]
The model I trained according to your method was all black in the test. May I ask if this is the reason above? @ahounkanrin
