### ISSUE TITLE
so文件

### ISSUE THREAD

**Issue by candancecheng** [xtudbxk/em-adapt-tensorflow#3]
Traceback (most recent call last):
  File "E:/code/myresearch/deeplab/em-adapt-tensorflow-master/deeplab.py", line 9, in <module>
    from estep import estep as _estep
  File "E:\code\myresearch\deeplab\em-adapt-tensorflow-master\estep.py", line 14, in <module>
    estep_lib = cdll.LoadLibrary(libweaklabel_path)
  File "D:\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "D:\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by xtudbxk** [comment]
I only tested my code in Linux system. And I'm not familiar with windows system, and sorry that cann't help you. Maybe you can install a virtual linux machine by VMware or VirtualBox.

**Comment by candancecheng** [comment]
ok ,but another error      kryerror: fc6         Is it a model problem

**Comment by lumingliao** [comment]
> ok ,but another error kryerror: fc6 Is it a model problem

hello, I've been looking at this code recently. But I can't find the address of the init.npy. Can you help me to give a link, thanks.

**Comment by lumingliao** [comment]
> I only tested my code in Linux system. And I'm not familiar with windows system, and sorry that cann't help you. Maybe you can install a virtual linux machine by VMware or VirtualBox.

 I can't find the address of the init.npy. Can you help me to give a Specific address, thanks.

**Comment by xtudbxk** [comment]
@candancecheng I have no idea due to the limited information about the question. Maybe you can offer more information about it or try again using the offered init.npy (see link below).
@lumingliao You can refer to my another project [SEC-tensorflow](https://github.com/xtudbxk/SEC-tensorflow) for the download link. And it seems the same according to my memory.

**Comment by candancecheng** [comment]
shape:x,y (?, 321, 321, 3) (?, 321, 321, 1)
shape:data_x,data_y (6, 321, 321, 3) (6, 321, 321, 3)
Traceback (most recent call last):
  File "/media/can/66E0-67D8/em-adapt-tensorflow-master/deeplab.py", line 295, in <module>
    adapt.train(base_lr=0.001,weight_decay=1e-5,momentum=0.9,batch_size=batch_size,epoches=epoches)
  File "/media/can/66E0-67D8/em-adapt-tensorflow-master/deeplab.py", line 268, in train
    self.sess.run(self.net["accum_gradient_accum"],feed_dict=params)
  File "/home/can/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/can/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (6, 321, 321, 3) for Tensor 'placeholder_1/Placeholder_1:0', which has shape '(?, 321, 321, 1)'
it happened here：
print('shape:x,y',x.shape,y.shape)
data_x,data_y = self.sess.run([x,y],feed_dict={self.net["is_training"]:True})
print('shape:data_x,data_y',data_x.shape,data_y.shape,data_y[0])

Sorry, I don't know how to correct this problem. Can you help me

**Comment by xtudbxk** [comment]
It seems you use the colored images as the learning target. But in generally, we use the indexed images as target. So you should convert the colored images to the indexed images first.  In details, the indexed images map each categories to range [0, 20] and have a shape of [h,w,1].

---
To do it automatically for PASCAL VOC dataset, I just update some code in my server. But unfortunately, the server fails down until now. So the new code would update some hours later.

**Comment by candancecheng** [comment]
print('shape:x,y',x.shape,y.shape)   #shape:x,y (?, 321, 321, 3) (?, 321, 321, 1)
data_x,data_y = self.sess.run([x,y],feed_dict={self.net["is_training"]:True})
print('shape:data_x,data_y',data_x.shape,data_y.shape)   #shape:data_x,data_y (6, 321, 321, 3) (6, 321, 321, 3)

I use VOC data set, but the dimension changes after data_x,data_y = self.sess.run([x,y],feed_dict={self.net["is_training"]:True}) . I don't know why

**Comment by xtudbxk** [comment]
I just update the code for converting colored images in pascal voc dataset to indexed images. You can run "python converty.py" to do it. And it is important to note that the convert.py also contains a few code to process the SBD datasest. So maybe you should comment out those code.

---
Moreover, the dimension didn't change in `data_x,data_y = self.sess.run([x,y],feed_dict={self.net["is_training"]:True}) `. "(?,321,321,1)" is the inferred shape by tensorflow and "(6,321,321,3)" is the actual shape of "data_y".
